version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 5647382910
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"         # если порт занят — поменяй на "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build: .
    container_name: php_app
    volumes:
      - ../:/var/www/html                 # Монтируем КОРЕНЬ проекта rest/
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_MODE: "debug"                # можно быстро выключить, поставив "off"

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
