services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 5647382910
      MYSQL_DATABASE: rest_test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    user: "1000:1000"
    working_dir: /var/www
    build:
      context: .            # как и раньше
      dockerfile: Dockerfile
    container_name: php_api
    env_file:
      - ../.env
    ports:
      - "8080:80"           # Apache внутри слушает 80
    environment:
      DB_HOST: mysql
      DB_NAME: rest_test
      DB_USER: user
      DB_PASS: pass
      API_KEY: ${API_KEY}
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_MODE: "develop,debug"      # Xdebug возьмёт режим из env
      COMPOSER_MEMORY_LIMIT: "-1"
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ../public:/var/www/public
      - ../src:/var/www/src
      - ../composer.json:/var/www/composer.json
      - ../composer.lock:/var/www/composer.lock
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
